# .github/workflows/python-main.yml

name: Python Hello Workflow

# Trigger the workflow when code is pushed to the repository
on:
  push:
    branches:
      - main  # Change this to your default branch if it's not "main"
  pull_request:
    branches:
      - main  # You can adjust this if you want to trigger on PRs too

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # This sets up the job to run on the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out the code from your repository

    - name: Set up Python
      uses: actions/setup-python@v4  # This sets up a Python environment

      with:
        python-version: '3.x'  # Use the latest version of Python 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        # Add any dependencies here if needed (e.g., pandas, requests)
        pip install -r requirements.txt
    
    - name: Run python.py
      run: |
        python python.py  # This runs the hello.py script

